export = {
	env: {
		es2021: true,
		node: true,
		commonjs: true
	},
	extends: [
		'standard-with-typescript',
		'plugin:@typescript-eslint/recommended'
	],
	parser: '@typescript-eslint/parser',
	parserOptions: {
		ecmaVersion: 12,
		tsconfigRootDir: '.',
		project: './tsconfig.json',
		sourceType: 'script'
	},
	plugins: ['@typescript-eslint'],
	rules: {
		'@typescript-eslint/indent': ['error', 2],
		'@typescript-eslint/quotes': ['error', 'single'],
		'@typescript-eslint/semi': ['error', 'never'],
		'@typescript-eslint/strict-boolean-expressions': 'off',
    '@typescript-eslint/space-before-function-paren': 'off',
    '@typescript-eslint/ban-ts-comment': 'off',
    '@typescript-eslint/prefer-ts-expect-error': 'off',
		'@typescript-eslint/naming-convention': 'off',
		'@typescript-eslint/explicit-module-boundary-types': 'off',
		'@typescript-eslint/explicit-function-return-type': 'off',
		'no-fallthrough': 'off',
		'block-scoped-var': 'error',
		'brace-style': [2, '1tbs'],
		'eol-last': [2, 'always'],
    'no-empty-character-class': 'error',
		'no-new': 'off',
    'no-empty': 'error',
		eqeqeq: 'error',
		'linebreak-style': ['error', 'unix'],
		'no-console': 'off',
		'no-unused-vars': 'error',
		'no-extra-parens': 'error',
		'no-await-in-loop': 'error',
		'no-mixed-spaces-and-tabs': 'error',
		'no-void': 'off',
		'prefer-const': 'off',
		indent: ['error', 2],
		yoda: 'error',
    'no-extra-boolean-cast': 'error',
		'no-extra-semi': 'error',
		'no-func-assign': 'error',
		'no-inner-declarations': 'error',
		'no-invalid-regexp': 'error',
		'no-irregular-whitespace': 'error',
		'no-misleading-character-class': 'error',
		'no-obj-calls': 'error',
		'no-prototype-builtins': 'error',
		'no-regex-spaces': 'warn',
		'no-sparse-arrays': 'error',
		'no-template-curly-in-string': 'error',
		'no-unexpected-multiline': 'error',
		'no-unreachable': 'error',
		'no-unsafe-finally': 'error',
		'no-unsafe-negation': 'error',
		'require-atomic-updates': 'error',
		'use-isnan': 'error',
		'valid-typeof': 'error'
	}
}
